version: '3'

services:
  subscription:
    build: .
    container_name: subscription
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mylocal

  db:
    container_name: db
    image: postgres:alpine
    env_file:
      - ./.env # load environment variables from the file
    networks:
      - mylocal

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    environment:
      SWAGGER_JSON: /app/swagger.json
    volumes:
      # монтируем swagger.json для доступа внутри контейнера
      - ./internal/docs/swagger.json:/app/swagger.json
    networks:
      - mylocal

networks:
  mylocal:
    driver: bridge
